name: SkyGrid
authors: [Barry1990, Ktesibios]
version: 1.0.1


load: STARTUP
main: me.barry1990.skygrid.SkyGrid


commands:
  home:
    description: Teleport to your home.
    aliases: [h]
    usage: §4 Usage §6/home <homename>.
  sethome:
    description: Set new a home or move an existing home.
    aliases: [seth, homeset]
    usage: §4 Usage §6/sethome <homename>.
  deletehome:
    description: Delete a home
    aliases: [delhome, homedel, homedelete]
    usage: §4 Usage §6/deletehome <homename>.
  listhomes:
    description: Get a list of your homes
    aliases: [listhome, homelist]
    usage: §4 Usage §6/deletehome <homename>.
  invitehome:
    description: Invite a player to your home
    aliases: [homeinvite, hinv]
    usage: §4 Usage §6/invitehome <playername> <homename>.